# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossGoreleaserAction < Formula
  desc ""
  homepage ""
  version "0.0.1-alpha-875ec3d311d39aafe7d42eae7bdabeb42ec9592d"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tmknom/cross-goreleaser-action/releases/download/v0.0.1-alpha-875ec3d311d39aafe7d42eae7bdabeb42ec9592d/cross-goreleaser-action_0.0.1-alpha-875ec3d311d39aafe7d42eae7bdabeb42ec9592d_darwin_amd64.tar.gz"
    sha256 "aa5ff81364c71956fd319575e8c2da00a684f47a5fd6f62d6115bb81714cabca"

    def install
      bin.install "cross-goreleaser-action"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tmknom/cross-goreleaser-action/releases/download/v0.0.1-alpha-875ec3d311d39aafe7d42eae7bdabeb42ec9592d/cross-goreleaser-action_0.0.1-alpha-875ec3d311d39aafe7d42eae7bdabeb42ec9592d_darwin_arm64.tar.gz"
    sha256 "e6d83701c213d169306d9ebfb769d9c8c671a2efde1f4a041722dc079845f442"

    def install
      bin.install "cross-goreleaser-action"
    end
  end
end
