# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlaygroundWorkflows < Formula
  desc "playground-workflows 0.10.0"
  homepage "https://github.com/tmknom/playground-workflows"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/playground-workflows/releases/download/v0.10.0/playground-workflows_0.10.0_darwin_amd64"
      sha256 "31c6a1c9dec206499596e485ea661a765f0876ce469dc43ffe221cddf0cae901"

      def install
        bin.install "playground-workflows_0.10.0_darwin_amd64" => "playground-workflows"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/playground-workflows/releases/download/v0.10.0/playground-workflows_0.10.0_darwin_arm64"
      sha256 "709ca154b0cf4eeb9a55d465ef1978479c715ad5b56e2b3f9955d2571b8e9d65"

      def install
        bin.install "playground-workflows_0.10.0_darwin_arm64" => "playground-workflows"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/playground-workflows/releases/download/v0.10.0/playground-workflows_0.10.0_linux_amd64"
        sha256 "5a45e9a9b63d1d734cf89b927d18aa23bc65a7b4679f2beca1846785b5ebc320"

        def install
          bin.install "playground-workflows_0.10.0_linux_amd64" => "playground-workflows"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/playground-workflows/releases/download/v0.10.0/playground-workflows_0.10.0_linux_arm64"
        sha256 "29480d1e9caf82a3f94bc759b606a955466d788ec5ac91f8a4516b563d9180a6"

        def install
          bin.install "playground-workflows_0.10.0_linux_arm64" => "playground-workflows"
        end
      end
    end
  end

  test do
    system "#{bin}/playground-workflows --version"
  end
end
