# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "test-goreleaser 0.22.4"
  homepage "https://github.com/tmknom/test-goreleaser"
  version "0.22.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.22.4/test-goreleaser_0.22.4_darwin_amd64"
      sha256 "f04eb79b81f680b58182ac774d23b1c121ab8064f43000b902f22eb2560ce26f"

      def install
        bin.install "test-goreleaser_0.22.4_darwin_amd64" => "test-goreleaser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.22.4/test-goreleaser_0.22.4_darwin_arm64"
      sha256 "c7819d75f2f403693a24c1396de27c8eb3fe8e410f34fc315058738aea2b5e4e"

      def install
        bin.install "test-goreleaser_0.22.4_darwin_arm64" => "test-goreleaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.22.4/test-goreleaser_0.22.4_linux_amd64"
        sha256 "6b7962d89f84f0d4d0401fd8f119e08aebb61e28fa8e8ac30ef46adccd7677ff"

        def install
          bin.install "test-goreleaser_0.22.4_linux_amd64" => "test-goreleaser"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.22.4/test-goreleaser_0.22.4_linux_arm64"
        sha256 "22a07a47467d4584fe9788631a51f1e6d5acced79062745f45e7d1c9866d7e4f"

        def install
          bin.install "test-goreleaser_0.22.4_linux_arm64" => "test-goreleaser"
        end
      end
    end
  end

  test do
    system "#{bin}/test-goreleaser --version"
  end
end
