# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "test-goreleaser 0.20.5"
  homepage "https://github.com/tmknom/test-goreleaser"
  version "0.20.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.20.5/test-goreleaser_0.20.5_darwin_amd64"
      sha256 "da1499a8f8b6cfa50b2e8c532e1d23d449e9de90ca3a9a329bf4fd990ef42d3c"

      def install
        bin.install "test-goreleaser_0.20.5_darwin_amd64" => "test-goreleaser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.20.5/test-goreleaser_0.20.5_darwin_arm64"
      sha256 "811cf3e73b42187a8d4617011739b220fd74a4f845283897249977b94ca9d6c2"

      def install
        bin.install "test-goreleaser_0.20.5_darwin_arm64" => "test-goreleaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.20.5/test-goreleaser_0.20.5_linux_amd64"
        sha256 "163335e18c3f97a9dac0e0cf0ceaa70f4d116003859e7068d4128609e655f67f"

        def install
          bin.install "test-goreleaser_0.20.5_linux_amd64" => "test-goreleaser"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.20.5/test-goreleaser_0.20.5_linux_arm64"
        sha256 "0d7800322318436668c9d6bf18f1264f545cfe8e6c3db0fc7242333413b228f6"

        def install
          bin.install "test-goreleaser_0.20.5_linux_arm64" => "test-goreleaser"
        end
      end
    end
  end

  test do
    system "#{bin}/test-goreleaser --version"
  end
end
