# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "test-goreleaser 0.24.0"
  homepage "https://github.com/tmknom/test-goreleaser"
  version "0.24.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.24.0/test-goreleaser_0.24.0_darwin_amd64"
      sha256 "463aaa9b5258356b33c889586f10851dbd6ff40d227e8703a52575f19ae48a39"

      def install
        bin.install "test-goreleaser_0.24.0_darwin_amd64" => "test-goreleaser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmknom/test-goreleaser/releases/download/v0.24.0/test-goreleaser_0.24.0_darwin_arm64"
      sha256 "690f3fd357f2ad582b3e734fe99676626b0ac6d91032f797085535214b2ea51b"

      def install
        bin.install "test-goreleaser_0.24.0_darwin_arm64" => "test-goreleaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.24.0/test-goreleaser_0.24.0_linux_amd64"
        sha256 "65596dc54adeea32915910b175960049b5d6c4bb7f33130b71ba4b7cd84c64c4"

        def install
          bin.install "test-goreleaser_0.24.0_linux_amd64" => "test-goreleaser"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmknom/test-goreleaser/releases/download/v0.24.0/test-goreleaser_0.24.0_linux_arm64"
        sha256 "31eba041730dbcf6432e1fc4b149fd3789c2f637312fcbb1bcae2bc6dbbcb934"

        def install
          bin.install "test-goreleaser_0.24.0_linux_arm64" => "test-goreleaser"
        end
      end
    end
  end

  test do
    system "#{bin}/test-goreleaser --version"
  end
end
